# 🚀 NumPy: Zero to Placement-Ready Masterclass

Welcome! This notebook will take you from absolute zero to an advanced beginner/placement-ready level in **NumPy** (Numerical Python).

### How to use this notebook:
- **Read the theory**: Simple and beginner-friendly.
- **Run the code cells**: Understand the outputs.
- **Solve the mini-tasks**: Hands-on practice.
- **Read Interview Revision Notes**: Important points frequently asked in Data Science interviews!

## 1. Basics
### 🧠 Theory
* **What is NumPy?** NumPy stands for Numerical Python. It is the core library for scientific computing in Python.
* **Why use NumPy?** It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the foundation for pandas, scikit-learn, and basically all of ML in Python.
* **Difference between Python List and NumPy Array:**
  * NumPy arrays are **faster** because they are stored in continuous memory locations (C-type arrays).
  * NumPy arrays consume **less memory**.
  * NumPy arrays have a **fixed type** (e.g., all integers or all floats), while Python lists can contain mixed types.
  
Let's import NumPy. The standard convention is to import it as `np`.

In [2]:
import numpy as np
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


In [3]:
# Creating a basic list vs numpy array
my_list = [1, 2, 3, 4, 5]
my_array = np.array([1, 2, 3, 4, 5])

print("List:", my_list)
print("Array:", my_array)
print("Type of Array:", type(my_array))

List: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]
Type of Array: <class 'numpy.ndarray'>


### 📝 Mini Practice Task 1
Create a Python list containing the numbers 10, 20, 30. Convert this list to a NumPy array and print it.

In [4]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: Why is NumPy faster than Python lists?**
A: NumPy arrays are densely packed arrays of homogeneous type. Python lists are essentially arrays of pointers to objects spread across memory. NumPy operations are implemented in C, avoiding Python's loop overhead (Vectorization).

## 2. Array Creation
### 🧠 Theory
You don't always need to create arrays from existing lists. NumPy provides built-in functions to quickly generate arrays of specific shapes and values.
* `np.array()`: Create from a list.
* `np.zeros()`: Array filled with 0s.
* `np.ones()`: Array filled with 1s.
* `np.full()`: Array filled with a specific value.
* `np.arange()`: Similar to Python's `range()`, creates a sequence.
* `np.linspace()`: Creates an array with evenly spaced values over a specified interval.
* `np.eye()`: Identity matrix (useful in Linear Algebra).

In [5]:
# array() from list of lists (2D array)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", matrix)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# zeros, ones, and full
zeros_arr = np.zeros((2, 3)) # 2 rows, 3 columns
ones_arr = np.ones((3, 2))
full_arr = np.full((2, 2), 99)

print("Zeros:\n", zeros_arr)
print("\nOnes:\n", ones_arr)
print("\nFull:\n", full_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Full:
 [[99 99]
 [99 99]]


In [7]:
# Sequence arrays
seq_arr = np.arange(0, 10, 2) # start=0, stop=10(exclusive), step=2
lin_arr = np.linspace(0, 1, 5) # 5 values evenly spaced between 0 and 1
eye_arr = np.eye(3) # 3x3 identity matrix

print("Arange:", seq_arr)
print("Linspace:", lin_arr)
print("Identity Matrix:\n", eye_arr)

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 📝 Mini Practice Task 2
Create a 3x3 array filled with the number 7. Then create an array of 10 evenly spaced numbers between 10 and 20.

In [8]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: What is the difference between `arange` and `linspace`?**
A: `arange` takes a **step size** (like counting by 2s). `linspace` takes the **number of samples** you want between a start and end point. 

## 3. Array Properties
### 🧠 Theory
Once you have an array, you'll need to check its structure, especially when debugging ML models.
* `ndim`: Number of dimensions (1D, 2D, 3D...).
* `shape`: The shape of the array (rows, columns).
* `size`: Total number of elements.
* `dtype`: Data type of the elements (e.g., int32, float64).
* `itemsize`: The size in bytes of each element.
* `reshape()`: Changes the shape of the array without changing its data.

In [9]:
arr = np.array([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

print("Array:\n", arr)
print("Number of dimensions (ndim):", arr.ndim)
print("Shape (rows, cols):", arr.shape)
print("Total elements (size):", arr.size)
print("Data type (dtype):", arr.dtype)
print("Item size in bytes:", arr.itemsize)

Array:
 [[1.5 2.5 3.5]
 [4.5 5.5 6.5]]
Number of dimensions (ndim): 2
Shape (rows, cols): (2, 3)
Total elements (size): 6
Data type (dtype): float64
Item size in bytes: 8


In [10]:
# Reshaping
flat_arr = np.arange(1, 13) # 1 to 12
reshaped_arr = flat_arr.reshape((3, 4)) # 3 rows, 4 columns

print("Original 1D:", flat_arr)
print("Reshaped 2D:\n", reshaped_arr)

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 📝 Mini Practice Task 3
Create an array of numbers from 1 to 15. Then, reshape it into a 3x5 matrix and print its `shape` attribute.

In [11]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: What happens if you try to `reshape` an array of size 12 into a `(5,3)` shape?**
A: It will throw a `ValueError`. The total number of elements must remain exactly the same (12 != 15). Note: You can use `-1` in reshape (e.g., `.reshape(3, -1)`) and NumPy will automatically calculate the missing dimension!

## 4. Indexing and Slicing
### 🧠 Theory
Extracting specific values or chunks of an array.
* **1D Indexing:** Same as Python lists (`arr[0]`).
* **2D Indexing:** `arr[row, col]` (unlike lists which use `list[row][col]`).
* **Negative Indexing:** `-1` accesses the last element.
* **Slicing:** `arr[start:stop:step]`.

In [12]:
arr_1d = np.array([10, 20, 30, 40, 50])
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])
print("Slice [1:4]:", arr_1d[1:4])
print("Step slice [::2]:", arr_1d[::2]) # Every 2nd element

First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Step slice [::2]: [10 30 50]


In [13]:
arr_2d = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

print("Element at row 1, col 2:", arr_2d[1, 2]) # 60
print("First row:", arr_2d[0, :])
print("First column:", arr_2d[:, 0])
print("Sub-matrix (top right 2x2):\n", arr_2d[0:2, 1:3])

Element at row 1, col 2: 60
First row: [10 20 30]
First column: [10 40 70]
Sub-matrix (top right 2x2):
 [[20 30]
 [50 60]]


### 📝 Mini Practice Task 4
Given a 4x4 array of random integers, extract the bottom-left 2x2 sub-matrix.

In [14]:
# Write your code here:


### 🎯 Interview Revision Note:
Slicing in NumPy creates a **view**, not a copy. If you modify a slice, the original array changes! To get a true copy, use `arr[...].copy()`.

## 5. Array Operations & Broadcasting
### 🧠 Theory
* **Element-wise operations**: In lists, `[1,2] + [3,4]` results in `[1,2,3,4]`. In NumPy, `np.array([1,2]) + np.array([3,4])` results in `[4,6]`. It does math!
* **Broadcasting**: NumPy's superpower! It allows math operations between arrays of different shapes (e.g., adding a scalar to a matrix).

In [15]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)
print("Modulus:", b % 3)

Addition: [11 22 33]
Subtraction: [ -9 -18 -27]
Multiplication: [10 40 90]
Division: [0.1 0.1 0.1]
Power: [1 4 9]
Modulus: [1 2 0]


In [16]:
# Broadcasting example
matrix = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
vector = np.array([100, 200, 300])

print("Matrix + Scalar:\n", matrix + scalar)
print("\nMatrix + Vector (Broadcast across rows):\n", matrix + vector)

Matrix + Scalar:
 [[11 12 13]
 [14 15 16]]

Matrix + Vector (Broadcast across rows):
 [[101 202 303]
 [104 205 306]]


### 📝 Mini Practice Task 5
Create an array of prices `[100, 200, 300]`. Apply a 15% discount to all prices using a single math operation (vectorization).

In [17]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: Explain Broadcasting.**
A: Broadcasting allows NumPy to perform arithmetic on arrays of different shapes. The smaller array is "broadcast" (padded) across the larger array so they have compatible shapes. This is highly optimized and avoids Python loops.

## 6. Mathematical Functions
### 🧠 Theory
NumPy provides blazing-fast statistical and mathematical functions.
* `sum()`, `mean()`, `median()`, `min()`, `max()`
* `std()` (standard deviation), `var()` (variance)
* `sqrt()`, `exp()`, `log()`
You can apply these to the whole array, or along specific **axes** (axis 0 = columns, axis 1 = rows).

In [18]:
arr = np.array([[1, 5, 3], 
                [4, 2, 6]])

print("Sum overall:", np.sum(arr))
print("Sum of each column (axis=0):", np.sum(arr, axis=0))
print("Sum of each row (axis=1):", np.sum(arr, axis=1))

print("\nMean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))

Sum overall: 21
Sum of each column (axis=0): [5 7 9]
Sum of each row (axis=1): [ 9 12]

Mean: 3.5
Max: 6
Standard Deviation: 1.707825127659933


In [19]:
# Universal Functions (ufuncs)
arr2 = np.array([1, 4, 9])
print("Square root:", np.sqrt(arr2))
print("Exponential (e^x):", np.exp(arr2))

Square root: [1. 2. 3.]
Exponential (e^x): [2.71828183e+00 5.45981500e+01 8.10308393e+03]


### 📝 Mini Practice Task 6
Find the mean and maximum value of the array `x = np.array([12, 45, 67, 89, 34, 55])`.

In [20]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: Axis=0 vs Axis=1?**
A: `axis=0` acts along the columns (vertically down). `axis=1` acts along the rows (horizontally across). Think of the axis as the direction that gets collapsed.

## 7. Iteration
### 🧠 Theory
While you should avoid looping over NumPy arrays (use vectorization instead!), sometimes you have to.
* `for x in arr`: Loops over the first dimension.
* `np.nditer()`: Elegant way to loop through every single element of an n-dimensional array.

In [21]:
arr2d = np.array([[1, 2], [3, 4]])

# Normal loop gives rows
print("Normal loop:")
for row in arr2d:
    print(row)

# nditer gives individual elements
print("\nnditer loop:")
for x in np.nditer(arr2d):
    print(x, end=" ")

Normal loop:
[1 2]
[3 4]

nditer loop:
1 2 3 4 

### 📝 Mini Practice Task 7
Use `nditer` to print all elements of a 3D array: `np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])`

In [22]:
# Write your code here:


### 🎯 Interview Revision Note:
Looping in Python is slow. If you find yourself writing a `for` loop over a large NumPy array, there is almost always a vectorized NumPy function that does it 100x faster.

## 8. Shape Manipulation (Reshape vs Resize vs Flatten vs Ravel)
### 🧠 Theory
* `reshape()`: Returns a new array with a new shape (doesn't modify original).
* `resize()`: Modifies the array *in-place*.
* `flatten()`: Returns a 1D *copy* of the array.
* `ravel()`: Returns a 1D *view* of the array (memory efficient, changes affect original).
* `transpose` or `.T`: Swaps rows and columns.

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Original:\n", arr)
print("\nTransposed (.T):\n", arr.T)

flat = arr.flatten() # Copy
rav = arr.ravel()    # View
rav[0] = 999         # Changing ravel affects the original array!

print("\nAfter modifying ravel view, original array becomes:\n", arr)

Original:
 [[1 2 3]
 [4 5 6]]

Transposed (.T):
 [[1 4]
 [2 5]
 [3 6]]

After modifying ravel view, original array becomes:
 [[999   2   3]
 [  4   5   6]]


### 📝 Mini Practice Task 8
Create an array of shape (2,3), transpose it, and then flatten it to a 1D array.

In [24]:
# Write your code here:


### 🎯 Interview Revision Note:
**Q: `flatten()` vs `ravel()`?**
A: `flatten()` returns a deep copy. It is safer but uses more memory. `ravel()` mostly returns a view. It is faster and uses less memory, but changing it might corrupt your original data!

## 9. Combining and Splitting Arrays
### 🧠 Theory
Machine Learning often requires joining datasets (e.g., combining features and target variables).
* `np.concatenate()`: Joins along an existing axis.
* `np.vstack()`: Vertical stack (row-wise).
* `np.hstack()`: Horizontal stack (column-wise).
* `np.split()`: Splits one array into multiple sub-arrays.

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Horizontal Stack (hstack):", np.hstack((a, b)))
print("Vertical Stack (vstack):\n", np.vstack((a, b)))

Horizontal Stack (hstack): [1 2 3 4 5 6]
Vertical Stack (vstack):
 [[1 2 3]
 [4 5 6]]


In [26]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Concatenate along columns (axis=1)
print("Concatenate axis=1:\n", np.concatenate((mat1, mat2), axis=1))

# Split
arr_to_split = np.array([10, 20, 30, 40, 50, 60])
print("\nSplit array into 3 equal parts:", np.split(arr_to_split, 3))

Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

Split array into 3 equal parts: [array([10, 20]), array([30, 40]), array([50, 60])]


### 📝 Mini Practice Task 9
Stack two 1D arrays `[1,1,1]` and `[2,2,2]` vertically to create a 2x3 matrix.

In [27]:
# Write your code here:


## 10. Boolean Masking & Filtering
### 🧠 Theory
This is the most common way to filter data in pandas and NumPy. You create a condition which returns an array of `True/False`, and use that as an index!
* `arr[arr > 5]`: Returns all elements greater than 5.
* `np.where(condition, x, y)`: Returns `x` if condition is true, else `y`.

In [28]:
arr = np.array([1, 20, 15, 3, 50, 8, 12])

# Step 1: Create the boolean mask
mask = arr > 10
print("Boolean Mask:", mask)

# Step 2: Use mask to filter
print("Filtered Array (values > 10):", arr[mask])

# where() example: Replace values < 10 with 0, else keep original
new_arr = np.where(arr < 10, 0, arr)
print("Using np.where():", new_arr)

Boolean Mask: [False  True  True False  True False  True]
Filtered Array (values > 10): [20 15 50 12]
Using np.where(): [ 0 20 15  0 50  0 12]


### 📝 Mini Practice Task 10
Given `arr = np.array([10, -5, 20, -1, 30])`, filter out all negative numbers so you are left with `[10, 20, 30]`.

In [29]:
# Write your code here:


## 11. Sorting and Searching
### 🧠 Theory
* `np.sort()`: Sorts elements.
* `np.argsort()`: Very important in ML! Returns the **indices** that would sort the array.
* `np.unique()`: Returns unique elements.
* `np.argmax()` / `np.argmin()`: Returns the index of the max/min value.

In [30]:
arr = np.array([30, 10, 50, 20, 40])

print("Sorted array:", np.sort(arr))
print("Argsort (indices of sorted elements):", np.argsort(arr))
print("Index of maximum value (argmax):", np.argmax(arr))

Sorted array: [10 20 30 40 50]
Argsort (indices of sorted elements): [1 3 0 4 2]
Index of maximum value (argmax): 2


In [31]:
animals = np.array(["cat", "dog", "cat", "bird", "dog", "dog"])
print("Unique animals:", np.unique(animals))

Unique animals: ['bird' 'cat' 'dog']


### 📝 Mini Practice Task 11
Find the index of the minimum value in `[99, 45, 12, 88, 5]`. (Hint: use argmin).

In [32]:
# Write your code here:


## 12. Linear Algebra Basics
### 🧠 Theory
Deep Learning relies heavily on matrices.
* `np.dot()` or `@`: Matrix multiplication / Dot product.
* `np.linalg.inv()`: Inverse of a matrix.
* `np.linalg.det()`: Determinant of a matrix.

In [33]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

# Dot Product (Matrix Multiplication)
print("Dot Product:\n", np.dot(A, B))
# Alternatively: print(A @ B)

# Inverse
print("\nInverse of A:\n", np.linalg.inv(A))

# Determinant
print("\nDeterminant of A:", np.linalg.det(A))

Dot Product:
 [[19 22]
 [43 50]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of A: -2.0000000000000004


### 📝 Mini Practice Task 12
Multiply a 1x2 vector `[[1, 2]]` with a 2x1 vector `[[3], [4]]` using `np.dot()`.

In [34]:
# Write your code here:


## 13. Random Module
### 🧠 Theory
Used constantly to initialize neural network weights, create dummy data, or split train/test sets.
* `np.random.rand()`: Uniform distribution [0,1).
* `np.random.randn()`: Normal distribution (mean 0, variance 1).
* `np.random.randint()`: Random integers.
* `np.random.seed()`: Ensures reproducibility (you get the same random numbers).

In [35]:
np.random.seed(42) # Set seed for reproducibility

print("Random floats [0,1):\n", np.random.rand(2, 2))
print("\nRandom Standard Normal distribution:\n", np.random.randn(2))
print("\nRandom integers between 1 and 100:\n", np.random.randint(1, 100, size=(10,)))

Random floats [0,1):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]

Random Standard Normal distribution:
 [-0.23415337 -0.23413696]

Random integers between 1 and 100:
 [75 75 88 24  3 22 53  2 88 30]


### 📝 Mini Practice Task 13
Generate an array of 5 random integers between 10 and 50.

In [36]:
# Write your code here:


## 14. Real-world ML Relevance
### 🧠 Theory
How is this actually used?
1. **Feature Matrix ($X$) & Target Vector ($y$)**: ML datasets are loaded into 2D NumPy arrays ($X$) and 1D arrays ($y$).
2. **Min-Max Scaling / Normalization**: Bringing all features to a scale of 0 to 1 to help algorithms converge faster. Uses vectorized operations.

In [37]:
# Dummy ML Feature Matrix X (3 samples, 2 features: age & salary)
X = np.array([
    [25, 50000],
    [35, 80000],
    [45, 120000]
])

# Normalization formula: X_scaled = (X - X_min) / (X_max - X_min)
# Notice how we specify axis=0 to find max/min for EACH column independently!
X_min = np.min(X, axis=0)
X_max = np.max(X, axis=0)

X_scaled = (X - X_min) / (X_max - X_min)

print("Original Data:\n", X)
print("\nNormalized Data (Values are between 0 and 1):\n", X_scaled)

Original Data:
 [[    25  50000]
 [    35  80000]
 [    45 120000]]

Normalized Data (Values are between 0 and 1):
 [[0.         0.        ]
 [0.5        0.42857143]
 [1.         1.        ]]


## 15. Mini Project: Sales Performance Analysis
### 📊 Task:
You are given the sales data (in thousands of dollars) for 3 products over 4 quarters. 
Analyze the data using NumPy!

Data:
Product A: Q1=10, Q2=15, Q3=12, Q4=20
Product B: Q1=5, Q2=8, Q3=9, Q4=14
Product C: Q1=22, Q2=20, Q3=25, Q4=28

In [38]:
# Setup
sales = np.array([
    [10, 15, 12, 20], # Prod A
    [5,  8,  9,  14], # Prod B
    [22, 20, 25, 28]  # Prod C
])

# 1. Total sales for each product across all quarters?
total_per_product = np.sum(sales, axis=1)
print("Total sales per product (A, B, C):", total_per_product)

# 2. Total sales across all products for each quarter?
total_per_quarter = np.sum(sales, axis=0)
print("Total sales per quarter (Q1, Q2, Q3, Q4):", total_per_quarter)

# 3. Find the maximum sales in a single quarter for Product C (Index 2)
max_prod_c = np.max(sales[2, :])
print("Max sales in a quarter for Product C:", max_prod_c)

# 4. Which product had the lowest overall total sales? (Hint: argmin)
worst_product_idx = np.argmin(total_per_product)
product_names = ["Product A", "Product B", "Product C"]
print("Worst performing product:", product_names[worst_product_idx])

# 5. Was there any quarter where sales for Product A exceeded 18k?
did_exceed = np.any(sales[0, :] > 18)
print("Did Product A ever exceed 18k?", did_exceed)

Total sales per product (A, B, C): [57 36 95]
Total sales per quarter (Q1, Q2, Q3, Q4): [37 43 46 62]
Max sales in a quarter for Product C: 28
Worst performing product: Product B
Did Product A ever exceed 18k? True


## 16. Placement / Interview Revision Notes 🏆

Before heading into your technical Data Science interview, review this rapid-fire list:

1. **Python List vs. NumPy Array:**
   - **Data**: Lists can contain mixed types; Arrays must be homogeneous (same type).
   - **Memory**: Arrays are densely packed in contiguous memory (C-style), lists are arrays of pointers. Arrays save memory.
   - **Speed**: Arrays are vastly faster due to Vectorization (operations happen in C, bypassing Python loops).

2. **`reshape` vs. `resize`:**
   - `reshape()`: Returns a *new* array with the new shape. The original array is unchanged.
   - `resize()`: Changes the shape of the array *in-place*. 

3. **`flatten` vs. `ravel`:**
   - `flatten()`: Returns a 1D **copy**. Modifying the flattened array will NOT change the original.
   - `ravel()`: Returns a 1D **view** (most of the time). Modifying it WILL change the original data. `ravel()` is faster and more memory efficient since it doesn't copy data.

4. **Vectorization & Broadcasting:**
   - **Vectorization**: Performing operations on entire arrays without writing explicit `for` loops in Python.
   - **Broadcasting**: A mechanism that allows NumPy to perform arithmetic on arrays of unequal shapes by implicitly "stretching/padding" the smaller array.
   
5. **Axis 0 vs Axis 1:**
   - By default, applying an aggregate function like `.sum()` squashes the whole array into a scalar.
   - Passing `axis=0` reduces the rows (giving you column totals).
   - Passing `axis=1` reduces the columns (giving you row totals).
   
### You made it! 🎉 
You are now officially Placement-Ready in NumPy basics!