# Task 1 — Create arrays

In [109]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

In [110]:
print(a)
print()
print(b)

[10 20 30 40 50]

[1 2 3 4 5]


# Task 2 — Basic operations

### Perform:

* addition
* subtraction
* multiplication
* division

In [111]:
#addition
print(f'The addition of a and b is {a+b}\n')

# subtraction
print(f'The subtraction of a and b is {a-b}\n')

# multiplication
print(f'The multiplication of a and b is {a*b}\n')

# division
print(f'The division of a and b is {a/b}\n')

The addition of a and b is [11 22 33 44 55]

The subtraction of a and b is [ 9 18 27 36 45]

The multiplication of a and b is [ 10  40  90 160 250]

The division of a and b is [10. 10. 10. 10. 10.]



# Task 3 — 2D array

### Find:

* shape
* size
* dimensions

In [112]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
print("The shape of the array is : ",arr.shape,'\n')
print("The size of the array is : ",arr.size,'\n')
print("The dimensions of the array is : ",arr.ndim,'\n')

The shape of the array is :  (2, 3) 

The size of the array is :  6 

The dimensions of the array is :  2 



# Task 4 — Indexing & slicing

### Get:

* first row
* second column
* element 5

In [115]:
print("The first row of the array is : ",arr[0],'\n')
print("The second column of the array is : ",arr[:,1],'\n')
print("The fifth element of the array is : ",arr[1,1] ,'\n')

The first row of the array is :  [1 2 3] 

The second column of the array is :  [2 5] 

The fifth element of the array is :  5 



# Task 5 — Aggregations

### On array a:

* sum
* mean
* max
* min

In [116]:
a = np.arange(20)
print(a)

print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
190
9.5
19
0


# Task 6 — Reshaping

#### arr = np.array([1,2,3,4,5,6])
#### 2 rows × 3 columns

In [117]:
arr = np.array([1,2,3,4,5,6])

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# Task 7 — Random numbers

### Create:

* 5 random numbers
* 3×3 random matrix

In [118]:
# arr = np.arange(5)
arr = np.random.randn(5)
arr

array([-0.08979682,  0.49297825, -1.33082916, -1.86830228,  1.2711329 ])

In [119]:
matrix = np.random.randn(3,3)
matrix

array([[ 0.78230731, -0.22102849, -0.28702289],
       [ 0.0120722 , -0.49646539, -0.80597097],
       [-1.00655205, -1.27517545,  0.78674378]])

# Task 8 — Filtering

### From array a, get values:

### greater than 25

In [97]:
a = np.arange(0,40,np.random.randint(1,8))
a

a[a>25]

array([27, 30, 33, 36, 39])

# Task 9 — Broadcasting

### arr = np.array([1,2,3])

### Add 10 to all elements

In [98]:
arr = np.array([1,2,3])
arr + 10

array([11, 12, 13])

# Task 10 — Real mini problem

### Given:

##### prices = np.array([100, 200, 300, 400])
##### quantity = np.array([1, 2, 1, 3])

### Find:

##### total revenue per product
##### total revenue overall

In [105]:
prices = np.array([100, 200, 300, 400])
quantity = np.array([1, 2, 1, 3])

total_revenue_per_product =  prices * quantity

total_revenue_overall = total_revenue_per_product.sum()

print(total_revenue_per_product)
print(total_revenue_overall)

[ 100  400  300 1200]
2000


#

# THE FINAL ROUND THE FINAL SET

#

## Q1 — Conditional + Aggregation
#### arr = np.array([12, 45, 67, 23, 89, 34, 90])

##### Find:

* mean of values greater than 50
* count of values less than 30
## Q2 — Combined Filtering
#### arr = np.arange(1, 51)

##### Get all numbers:

* divisible by 3
* AND greater than 20
## Q3 — 2D Array Logic
#### arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

##### Find:

* sum of each row
* max value in each column
## Q4 — Reshape + Logic
#### arr = np.arange(1, 13)

##### Tasks:

* reshape into 3×4
* find row-wise mean
## Q5 — Broadcasting + Condition
#### arr = np.array([5, 10, 15, 20])

##### Tasks:

* add 5 to all elements
* then return only values greater than 20
## Q6 — Mini Real Problem
#### marks = np.array([45, 67, 89, 32, 76, 50])

##### Find:

* total marks
* average marks
* number of students scoring above average
## Q7 — Slightly Twisted (important)
#### arr = np.array([2, 4, 6, 8, 10])

##### Create a new array where:

* if number is divisible by 4 → multiply by 2
* else → keep it as it is

In [125]:
# 1.

arr = np.array([12, 45, 67, 23, 89, 34, 90])

mean = arr[arr>50].mean()
count = arr[arr<30].size

In [146]:
# 2. 

arr = np.arange(1, 51)

arr[(arr%3 == 0) & (arr>20)]



array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [155]:
# 3. 

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

arr[:].sum(axis=1)

arr[:].max(axis=0)

array([70, 80, 90])

In [ ]:
# 4. 

arr = np.arange(1, 13)

reshaped_arr = arr.reshape(3,4)

reshaped_arr.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [ ]:
# 5. 

arr = np.array([5, 10, 15, 20])

modified_arr = arr + 5

modified_arr[modified_arr>20]

array([25])

In [165]:
# 6.


marks = np.array([45, 67, 89, 32, 76, 50])

total = marks.sum()

avg = marks.mean()

marks[marks>avg].size

3

In [172]:
# 7. 

arr = np.array([2, 4, 6, 8, 10])

# new_arr = arr*2 if (arr[arr%4 == 0]) else arr    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# This fails because:

# Python if works on single boolean
# NumPy needs element-wise condition


new_arr = np.where(arr % 4 == 0, arr * 2, arr)

new_arr

array([ 2,  8,  6, 16, 10])