# Fundamntal library for all the scientific  calculations in python on top of which many bibraries are made including pandas

#

#

## What is numpy ?  

It is a multi dimentional array library

which can store the data in 1D 2D 3D .... ARRAYS 

# How are lists different from numpy ?

lists - very slow 
numpy - very fast

# Why is Numpy Faster ?

* cz its Fixed Type 
* Faster to read less bytes of memory
* no Type checking when iterating through objects
* numpy ustilizes contiguous memory 
    * that is in numpy the things are stored continuous in the memory unlike lists which are random
    * due to this continues storage it can use SIMD VECTOR PROCESSING which modern processors have 
    * Effective cache utilization due to shorter memory look ups

# How are Lists different from Numpy?

both has INSERTION, DELETION, APPENDING, CONCATENATION, ETC 

BUT Numpy has much more

#### like eg :

in list 

###### a = [1,2,3]
###### b= [4,5,6]
###### a*b     # error

but in numpy

###### a = np.array([1,2,3])
###### b = np.array([4,5,6])
###### a*b     # array([ 4, 10, 18])


and lot more !!!

# Applications of Numpy

* Mathematics (MATLAB Replacement)
* Plotting (Matplotlib)
* Backend (Pandas, Connect 4, Digital Photography)
* Machine Learning

# Code

In [2]:
import numpy as np

In [5]:
# 1D Array

a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
# 2D array

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get dimension

print(f'The dimention of variable a is {a.ndim}')
print(f'The dimention of variable b is {b.ndim}')

The dimention of variable a is 1
The dimention of variable b is 2


In [15]:
# Get Shape

b.shape       # This shows this is a 2,3 matrix 

# The first indexx is always for rows and the second is for columns 

(2, 3)

In [18]:
# Get Type 

print(f'The datatype of a is {a.dtype}')
print(f'The datatype of b is {b.dtype}')

The datatype of a is int64
The datatype of b is float64


In [25]:
# we can also define the datatype bits we want

a = np.array([1,2,3], dtype='int8')
b = np.array([1,2,3], dtype='int16')
c = np.array([1,2,3], dtype='int32')
d = np.array([1,2,3], dtype='int64')

print(f'a : {a.dtype}')
print(f'b : {b.dtype}')
print(f'c : {c.dtype}')
print(f'd : {d.dtype}')

a : int8
b : int16
c : int32
d : int64


In [30]:
# Get Size

print(f"Bytes comsumed by a : {a.itemsize}")
print(f"Bytes comsumed by b : {b.itemsize}")
print(f"Bytes comsumed by c : {c.itemsize}")
print(f"Bytes comsumed by d : {d.itemsize}")

Bytes comsumed by a : 1
Bytes comsumed by b : 2
Bytes comsumed by c : 4
Bytes comsumed by d : 8


In [31]:
# Get The total number of element or size

a.size

3

In [38]:
# flotes are bigger than int in memory

a= np.array([1,2,34,5,6,7])
b= np.array([1.0,2.0,3.0,4.0,5.0,6.0,7.0])

print(f'The datatype of a is {a.dtype}  and memory size is {a.nbytes}')
print(f'The datatype of b is {b.dtype}  and memory size is{b.nbytes}')

The datatype of a is int64  and memory size is 48
The datatype of b is float64  and memory size is56


# Accessing/Changing specific elements, rows, columns, etc

In [40]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
# Get aspecific element [row,col]

# To access 13
print("With Positive indexing")

print(a[1, 5])

print()

print("With Negative indexing")

print(a[1, -2])

With Positive indexing
13

With Negative indexing
13


In [46]:
# Get a specific row

a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [47]:
# Get a spcific column

a[:, 3]

array([ 4, 11])

In [48]:
# Getting a little more fancy [startindex : endindex : stepsize]

a[0, 1 : 6 : 2]

array([2, 4, 6])

In [49]:
# To change a perticular value 

a[1,4] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


In [ ]:
# To change a perticular column with same values 

a[:, 3] = 5

print(a)

[[ 1  2  3  5  5  6  7]
 [ 8  9 10  5 20 13 14]]


In [54]:
# To change a perticular column with different values 
# The new shape should be equal to the original shape we cant give only one value to the column which has 2 rows when we are tying to change all the rows 

a[:,3] = [4,11]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]


# 3D array

In [58]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(f" The dimention of this array is : {b.ndim}")

print(b)

 The dimention of this array is : 3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Get specific element (work outside in)

print(b[0,1,1])

4


In [116]:
# idts that this(3d array) is important so i am skkipping this for now idk may be in future i will update this 

# 1D array is called as array and 2D array is called a matrix and anything above this is called tensor

# Initializing Different Types of Arrays

In [118]:
# All zero's

print(np.zeros(3))   # 1D array
print("That was 1st one\n\n")

print(np.zeros((3,3)))   # 2D array
print("That was 2nd one\n\n")

print(np.zeros((2,3)))   # 2D array
print("That was 3rd one\n\n")

print(np.zeros((2,3,3)))   # 3D array

[0. 0. 0.]
That was 1st one


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
That was 2nd one


[[0. 0. 0.]
 [0. 0. 0.]]
That was 3rd one


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [83]:
# All zeros

print(np.ones(3))   # 1D array
print("That was 1st one\n\n")

print(np.ones((3,3)))   # 2D array
print("That was 2nd one\n\n")

print(np.ones((2,3)))   # 2D array
print("That was 3rd one\n\n")

print(np.ones((2,3,4)))   # 3D array
print("That was 4th one\n\n")

[1. 1. 1.]
That was 1st one


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
That was 2nd one


[[1. 1. 1.]
 [1. 1. 1.]]
That was 3rd one


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
That was 4th one




In [82]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [111]:
a = np.zeros((3,3))
np.fill_diagonal(a,1)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [115]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# To create a empty array

np.empty((3,3))   # the values are just random for quick speed

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
np.empty(3)

array([0., 0., 0.])

In [122]:
print(np.arange(2,9,2))
print(np.arange(2,9,0.5))

[2 4 6 8]
[2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [123]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Sorting and Concatenation

In [124]:
arr = np.array([2,6,3,7,4,1])

np.sort(arr)

array([1, 2, 3, 4, 6, 7])

In [130]:
a = np.array([2,6,3,7,4,1])
b = np.array([2,3,5,66,6,])

np.concatenate((a,b))

array([ 2,  6,  3,  7,  4,  1,  2,  3,  5, 66,  6])

In [134]:
x = np.array([[1,2],[3,4]])
y= np.array([[5,6]])

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# Arange and Reshape

In [138]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [139]:
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

In [147]:
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [148]:
b.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [149]:
b.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [152]:
np.reshape(b,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [162]:
a = np.array([1,2,3,4,5,6])
a.ndim

1

In [161]:
a2 = a[np.newaxis]
a2.ndim

2

# Using condition based filtering

In [170]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
a<6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [172]:
a[a<6]

array([1, 2, 3, 4, 5])

In [173]:
a[(a>3) & (a<7)]

array([4, 5, 6])

In [175]:
x = np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [176]:
x = np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [195]:
a = np.arange(1,25).reshape((2,12))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [199]:
np.hsplit(a,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [200]:
np.hsplit(a,(2,4))

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

# View and Copies

In [201]:
# indexing sliceing are shallow copy so it is a view
# eg:

arr = np.arange(6)
b=arr

b[4] = 20

print(arr)
print(b)

[ 0  1  2  3 20  5]
[ 0  1  2  3 20  5]


In [202]:
# to create a deep copy we should use the keyword copy()

arr = np.arange(6)
b=arr.copy()

b[4] = 20

print(arr)
print(b)

[0 1 2 3 4 5]
[ 0  1  2  3 20  5]


In [209]:
a1 = np.arange(0,6)
a2 = np.arange(7,13)

print(a1)
print(a2)

[0 1 2 3 4 5]
[ 7  8  9 10 11 12]


In [210]:
a1+a2

array([ 7,  9, 11, 13, 15, 17])

In [211]:
a2-a1

array([7, 7, 7, 7, 7, 7])

In [212]:
a1 * a2

array([ 0,  8, 18, 30, 44, 60])

In [214]:
print(a2 / a1)

[       inf 8.         4.5        3.33333333 2.75       2.4       ]


C:\Users\mdzai\AppData\Local\Temp\ipykernel_23484\3537964833.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a2 / a1)


In [217]:
a1.sum()  # gives the sum of the values in the array

np.int64(15)

In [218]:
x = np.arange(1,10).reshape(3,3)
print(x)

x.sum(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [219]:
x.sum(axis=1)

array([ 6, 15, 24])

In [220]:
x.min()

np.int64(1)

In [221]:
x.max()

np.int64(9)

In [222]:
x.min(axis=0)

array([1, 2, 3])

In [223]:
x.max(axis=1)

array([3, 6, 9])

In [225]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [224]:
x.prod()

np.int64(362880)

In [226]:
x.prod(axis=0)

array([ 28,  80, 162])

In [227]:
x.prod(axis=1)

array([  6, 120, 504])

In [228]:
x.mean()

np.float64(5.0)

In [231]:
x.std(axis= 0)

array([2.44948974, 2.44948974, 2.44948974])

In [234]:
np.random.randint(1,10,(2,3))

array([[2, 5, 4],
       [6, 5, 2]], dtype=int32)

In [239]:
arr = np.arange(1,9).reshape(2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [240]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [242]:
arr.transpose().transpose()

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [243]:
elements = np.arange(1,10)
elements

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [245]:
np.flip(elements)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [265]:
n = np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [266]:
f = n.flatten() # converted the 2D array to 1D array
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [267]:
f[0] = 99
print(n)
print()
print(f)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[99  2  3  4  5  6  7  8  9]


In [268]:
n = np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [270]:
r = n.ravel()
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
r[0] = 99

print(n)
print()
print(r)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]

[99  2  3  4  5  6  7  8  9]


# How to go to documentations ?

In [272]:
help(object)

Help on class object in module builtins:

class object
 |  The base class of the class hierarchy.
 |
 |  When called, it accepts no arguments and returns a new featureless
 |  instance that has no instance attributes and cannot be given any.
 |
 |  Built-in subclasses:
 |      anext_awaitable
 |      async_generator
 |      async_generator_asend
 |      async_generator_athrow
 |      ... and 92 other subclasses
 |
 |  Methods defined here:
 |
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |
 |  __dir__(self, /)
 |      Default dir() implementation.
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Default object formatter.
 |
 |      Return str(self) if format_spec is empty. Raise TypeError otherwise.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getstate__(self, /)
 |      Helper for pickle.
 |
 |  __gt__(self, 

In [273]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



In [274]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

# like this u can go through all the documents of the attributes